version: '2'
services:
  mantis:
    image: sirminux/mantisbt
    restart: always
    build: .
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes: 
      - .:/var/www/html/
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantis
      - MYSQL_PASSWORD=mantis